<?php

$image = "gracie.jpg";
$lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum tincidunt erat porttitor elementum. Donec lacinia elit ligula, ut consectetur mauris laoreet non. Sed eget tempor diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi at lacus lobortis, hendrerit est at, tristique risus. Cras non sem varius, lacinia magna id, varius risus. Nullam sit amet diam vel nisi elementum pretium vitae nec elit. Pellentesque ullamcorper, justo ac molestie fringilla, lacus ex tempor erat, vel euismod elit felis sed turpis. Integer vel turpis mollis, pulvinar sem eget, pretium dui. Vivamus condimentum tortor sit amet semper lacinia. Donec blandit, erat cursus congue facilisis, diam enim scelerisque arcu, id semper massa odio sit amet libero. Aliquam eu ullamcorper magna. Ut egestas urna ut dolor placerat cursus. Duis pharetra elit vel ultrices lacinia. Aliquam non commodo magna. Phasellus laoreet eu libero sed convallis.

Nam sit amet luctus elit. Proin a ex ut magna aliquet tristique id a ligula. Proin faucibus molestie condimentum. Nullam rhoncus justo nec bibendum efficitur. In accumsan in diam non sagittis. Quisque at nisl ac orci tempus iaculis. Aliquam auctor tortor ligula, convallis imperdiet tortor posuere eu. Quisque vitae porttitor lorem, ut pretium est. Suspendisse dignissim lacus at lorem imperdiet, ac efficitur urna pharetra. Proin euismod, diam et pretium semper, elit ex ultricies odio, sit amet consequat metus odio quis velit. Proin vehicula risus non finibus ullamcorper. Duis at purus ullamcorper nunc pellentesque laoreet. Donec vulputate molestie neque non lobortis. Pellentesque vel consectetur justo, eu facilisis ligula.

Nullam elementum dapibus orci sit amet rhoncus. In interdum quam sed facilisis fermentum. Sed tellus massa, semper eget interdum at, maximus ut dolor. Sed at purus lobortis, dapibus orci quis, volutpat est. Quisque porta, nulla sit amet varius scelerisque, velit metus hendrerit sapien, quis eleifend lorem turpis et mauris. Nullam at porttitor massa. Donec posuere pellentesque risus, vel fermentum nisl. Integer fermentum, arcu vel euismod mollis, lorem felis bibendum orci, eu dapibus mauris tortor id orci. Duis cursus est ut leo luctus, eget convallis lorem bibendum. Fusce dignissim efficitur semper.

Phasellus gravida elementum sagittis. Vestibulum varius quam quam, eu interdum mauris cursus ac. Nullam vestibulum euismod pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur quis pulvinar enim. Quisque egestas condimentum ligula, a congue arcu tristique sit amet. Cras viverra, purus sed tristique varius, justo velit dignissim tellus, ut blandit lorem mi sed mi.

Phasellus tempor facilisis placerat. Nullam eu lacus in mauris fringilla tristique a non tortor. Phasellus tristique sem ut massa sodales gravida. Suspendisse sem urna, posuere id gravida ac, accumsan egestas ante. Ut eu dignissim elit. Praesent hendrerit nisl eu lacus bibendum, ut interdum risus elementum. Vivamus scelerisque dolor at lacus malesuada pretium. Duis porta porta metus vitae sagittis. Phasellus laoreet aliquam nisl sit amet ultrices. Phasellus quis nisi lobortis, malesuada dolor a, condimentum augue.";
?>